### ISSUE TITLE
Key bindings matching to keyboard, not X52 Pro

### ISSUE THREAD

**Issue by intenseorange** [spliffz/X52Elite_v3.3.0-beyond#8]
I’m not sure if I’m missing something, but I’ve spend four hours today trying to get this working. I’ve downloaded the latest Logitech software, make sure there was no profile loaded. I’ve moved the bind and profile file to where it is supposed to be installed. Went back into the Logitech software to open and press profile to load to HOTAS.

Once loaded all the keys are mapped but mapped to the keyboard not the x52 pro

The profile is pushed to the joystick and I have all three modes.

When I go into elite dangerous and goto select the control style it does not show v3.3.0.

Any help would be greatly appreciated.

**Comment by SAmundson07** [comment]
@intenseorange I"m pretty sure the issue your having is in relation to one of the fixes I implemented with the updated files on my github repository. Try using the files that I have at https://github.com/SAmundson07/Elite-Dangerous. This also includes several fixes for mismatched keybindings and profile issues I encountered after using it for a while.

**Comment by intenseorange** [comment]
Brilliant thank you for your advice. I’ll try and look at it tomorrow. I appreciate you getting back to me

**Comment by SAmundson07** [comment]
Not a problem, this should fix your problem as I ran into a similar issue when first trying to use it and did the troubleshooting to fix it. Let me know if this works out for you.

**Comment by LeeJacs** [comment]
Does it make sense that when i make just two changes (Full throttle, and remap reverse key to engine 75%) that everything seem to mess up?

**Comment by SAmundson07** [comment]
Well any re-mapping that is done will have to be done in both the HOTAS profile and keybinding in-game, with the exception of the sliders and axis movements on the throttle and joystick. Anything else can be re-mapped except the pinkie trigger since that is dedicated to the secondary action for each button. If the re-map is breaking things then your definitely missing a step somewhere.

**Comment by intenseorange** [comment]
@SAmundson07 - I had a bit of time after work, so I deleted everything I previously installed. Downloaded the new files, and followed the instructions meticulously.

IT WORKS. Thank you again. I'm very happy :) Printed all the reference sheets and now it time to learn. Thank you again

**Comment by SAmundson07** [comment]
@intenseorange that is great to hear, I was fairly certain I knew what the issue was which was fixed in the files I provided the link for. Glad to hear everything worked out for you! I'm not 100% sure whether the reference sheets are fully up to date with all the changes/additions I made since I created them, but they should be pretty close.

**Comment by intenseorange** [comment]
Awesome good to know. Thanks again
